baseURL = "https://jalict.com"
languageCode = "en-us"
title = "Frans Peter Larsen"
enableEmoji = true
enableGitInfo = true
googleAnalytics = "UA-40519567-6"
publishDir = "docs"

[imaging] 
resampleFilter = "CatmullRom"
resize = "960x q75"
quality = 75

[params]
description = "Frans Peter Larsen is a Unity and Unreal Engine, Game Developer based in Copenhagen."
images = ["profile.jpg"]
title = "Frans Peter Larsen Portfolio"